### ISSUE TITLE
Placement of encryption code causes performance issues

### ISSUE THREAD

**Issue by donnyv** [GusBeare/Nancy-UserManager#1]
I used this code a while back to get started with Nancy. I recently noticed there was a consistent performance issue for every request. I couldn't below 2 sec. I ran JetBrains dotTrace app and it said that the crypto service was causing issues. 

You should move it from RequestStartup to ApplicationStartup.

**Comment by GusBeare** [comment]
Hi Donny, many thanks for you input. Glad the code was of use to you.
I am under pressure on a project at the moment. Can you possibly provide the modified code so I can quickly update the project?

**Comment by GusBeare** [comment]
Finally got around to dealing with that. Should be fixed now.
